version: 2

builds:
  - main: .
    binary: bltctl
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/lu-zhengda/bltctl/cmd.version={{.Version}}

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - completions/*

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

homebrew_casks:
  - repository:
      owner: lu-zhengda
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Casks
    homepage: "https://github.com/lu-zhengda/bltctl"
    description: "macOS Bluetooth manager"
    license: "MIT"
    binaries:
      - bltctl
    completions:
      bash: completions/bltctl.bash
      zsh: completions/bltctl.zsh
      fish: completions/bltctl.fish
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bltctl"]
          end
